function fn_3D_image_plot (PROBE)

num_el = length(PROBE.ELEMENT_SHAPE);
PROBE.ELEMENT_MAJOR = [0 0.005 0];
PROBE.ELEMENT_MINOR = [2e-4; 0; 0];
PROBE_HEIGHT = 2;
grid on
axis([-0.02 0.02 -0.01 0.01 0 2.5])


% For each element
for el = 1:num_el
    hold on;
    % location of centre of each element:
    x = PROBE.ELEMENT_POSITION(1,el);
    y = PROBE.ELEMENT_POSITION(2,el);
    z = PROBE.ELEMENT_POSITION(3,el);
    
    % 4 points that define the size of each element
    p1 = [x-PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) z];
    p2 = [x+PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) z];
    p3 = [x+PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) z];
    p4 = [x-PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) z];
    X = [p1(1) p2(1) p3(1) p4(1)];
    Y = [p1(2) p2(2) p3(2) p4(2)];
    Z = [p1(3) p2(3) p3(3) p4(3)];
    patch(X, Y, Z);
    
end

% draw the probe itself:
% Side 1:
x = PROBE.ELEMENT_POSITION(1,1);
y = PROBE.ELEMENT_POSITION(2,1);
z = PROBE.ELEMENT_POSITION(3,1);
PROBE_P1 = [x-PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) z];
PROBE_P2 = [x-PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) z];
PROBE_P3 = [x-PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) PROBE_HEIGHT];
PROBE_P4 = [x-PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) PROBE_HEIGHT];
X = [PROBE_P1(1) PROBE_P2(1) PROBE_P3(1) PROBE_P4(1) PROBE_P1(1)];
Y = [PROBE_P1(2) PROBE_P2(2) PROBE_P3(2) PROBE_P4(2) PROBE_P1(2)];
Z = [PROBE_P1(3) PROBE_P2(3) PROBE_P3(3) PROBE_P4(3) PROBE_P1(3)];
s1 = patch(X,Y,Z,'black');
% make side mostly translucent
alpha(s1,0.05);

%Side 2:
x1 = PROBE.ELEMENT_POSITION(1,1);
x2 = PROBE.ELEMENT_POSITION(1,num_el);
y = PROBE.ELEMENT_POSITION(2,1);
z = PROBE.ELEMENT_POSITION(3,1);
PROBE_P1 = [x1-PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) z];
PROBE_P2 = [x2+PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) z];
PROBE_P3 = [x2+PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) PROBE_HEIGHT];
PROBE_P4 = [x1-PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) PROBE_HEIGHT];
X = [PROBE_P1(1) PROBE_P2(1) PROBE_P3(1) PROBE_P4(1) PROBE_P1(1)];
Y = [PROBE_P1(2) PROBE_P2(2) PROBE_P3(2) PROBE_P4(2) PROBE_P1(2)];
Z = [PROBE_P1(3) PROBE_P2(3) PROBE_P3(3) PROBE_P4(3) PROBE_P1(3)];
s2 = patch(X,Y,Z,'black');
alpha(s2,0.05);



%Side 3:
x1 = PROBE.ELEMENT_POSITION(1,1);
x2 = PROBE.ELEMENT_POSITION(1,num_el);
y = PROBE.ELEMENT_POSITION(2,1);
z = PROBE.ELEMENT_POSITION(3,1);
PROBE_P1 = [x1-PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) z];
PROBE_P2 = [x2+PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) z];
PROBE_P3 = [x2+PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) PROBE_HEIGHT];
PROBE_P4 = [x1-PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) PROBE_HEIGHT];
X = [PROBE_P1(1) PROBE_P2(1) PROBE_P3(1) PROBE_P4(1) PROBE_P1(1)];
Y = [PROBE_P1(2) PROBE_P2(2) PROBE_P3(2) PROBE_P4(2) PROBE_P1(2)];
Z = [PROBE_P1(3) PROBE_P2(3) PROBE_P3(3) PROBE_P4(3) PROBE_P1(3)];
s3 = patch(X,Y,Z,'black');
alpha(s3,0.05);

% Side 4:
x = PROBE.ELEMENT_POSITION(1,num_el);
y = PROBE.ELEMENT_POSITION(2,num_el);
z = PROBE.ELEMENT_POSITION(3,num_el);
PROBE_P1 = [x+PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) z];
PROBE_P2 = [x+PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) z];
PROBE_P3 = [x+PROBE.ELEMENT_MINOR(1) y+PROBE.ELEMENT_MAJOR(2) PROBE_HEIGHT];
PROBE_P4 = [x+PROBE.ELEMENT_MINOR(1) y-PROBE.ELEMENT_MAJOR(2) PROBE_HEIGHT];
X = [PROBE_P1(1) PROBE_P2(1) PROBE_P3(1) PROBE_P4(1) PROBE_P1(1)];
Y = [PROBE_P1(2) PROBE_P2(2) PROBE_P3(2) PROBE_P4(2) PROBE_P1(2)];
Z = [PROBE_P1(3) PROBE_P2(3) PROBE_P3(3) PROBE_P4(3) PROBE_P1(3)];
s4 = patch(X,Y,Z,'black');
alpha(s4,0.05);
hold off

end
